# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.
dist: xenial
language: python
python:
- '3.6'
cache:
  pip: true
env:
  - DEPLOY_PYPI="true"
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: fourstix
  password:
    secure: UK3CbjkS03U64C2c1J4nuJGJJKneRXTYAdn6rZ0sS0hkyDE0BhFIi0JZ4EYsM/HFP0VV09RMRHf1FsFRdYMlsBzM7gDdOEUmtPxHUknljPlUfE1KMx+LLfMh2K9tOvVQpEh5ZnvgmLbaLe+bNB+QAxBR4VOe72Sk4Dsaq+3vkkWpTxfMUc5CjLEgH3Gc2QOSr++TdFnPzhlRvMSls2RXfYklcBOYfof36dvPXvkaK602vopYJsNPJk/vznONq9myre8Rwnnj3CYejUPoYC7DPZMoWQDkCvj+E6OE440UhRdcrd4vZC0v8TVHD5ZxQKBJRO+w+4BntNL89/qmQAAu9HxrT/1y9KF/43awbJMeANDR7O4Po3/GMC3gpbXzv+Nw67umPkhY7bCV9CYwrbB4NfFeqlIVVCXF01aickp/qIlEEsFUA4toEaE7P98GVLZ+/4Uo1XYw6W0+eBzZUkZRpLXT3AG4DCxB0WkjCSmS/4CG3m2IPJ7L8e5P7q40TN1N7Y4QXAP4m2xSFlCWlsQLhPgnxBEsno6n+JwsP3YngFg1sGDrtulsU4joofQ3sEw9WdtlSaCSkR2Wbimxcwo53CC4jXPZLMgwZUSDLZareXuTi4ZGgJdGC3C17YKcmgSOVWVwFQnDPtfY0Rtu12xv9QnDs/p6O6WGUdnZSAn19PY=
  on:
    tags: true
    condition: $DEPLOY_PYPI = "true"
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint sparkfun_qwiicjoystick.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix sparkfun-circuitpython-qwiicjoystick
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
