dist: xenial
language: python
python:
- '3.6'
cache:
  pip: true
env:
  matrix:
  - DEPLOY_PYPI="true"
  global:
    secure: QVOfzSlwdYNi6QFJj2UoTo9MsiitYjxjjWxDK4pms0HW3lYPsLCTFnYpPd/iNau4JxqQFzA451xdTbzzk/wflxYsB4ruyXPvN/fi5oTHA/vlUo8Mm7Xui9udMtbi8ZCIyeEHFgEdaeeK/HydgIPFyQ8HJFphOMO6YdYWkcJYbJDxnNv76+lsrymdG9377dTDqzSXF05z4NbeaWjpyAC/h8uquMq/1H6xoddj9R/O7mJwuRIlxIVljkC4+i7WqW9mF2G9c1MeqTW3oAcKcIi7qe5JQrUoqVJCyG37maV31cTeWmLAEQ7YtdKXJzXC3/HX5ttoKPhvbqf5jNDPGRk1NLssWPqJzGIKViKfIXWTEQ6GqmoR77gn/fv1/lFt7t5+by4GML/l+sbDI4IaMZaXW9ZlZSdCpG1oPY4hjj1g+A98X10MFpcacFWTnqDb55xSe9LdKmRCwspQTPqq9a83TrosvoT74RxNsGy1d0L0bHlo3St1855aT+TQHG76KRC0pjYSv9TdWPqyNJ1mDBxXDGcLEE+W/Ph9GvNO1eCFxYVXq9Gm6Tu37Tyaf2TK5uzM8zWBWJ8ssDaWoK8tJJpHf7BwTUt/ALnSmMzLLKVJV8gigJJyYcctGY4Ipnn8pA3Bmp73mI24VMvkLXdO4RDJ3EcAcPHK6pxyUzFqNB6HmV4=
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: fourstix
  password:
    secure: 
  on:
    tags: true
    condition: $DEPLOY_PYPI = "true"
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint sparkfun_qwiicjoystick.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix sparkfun-circuitpython-qwiicjoystick
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
